// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiyjejkowcfvqjroxnos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeWplamtvd2NmdnFqcm94bm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTE4ODEsImV4cCI6MjA2OTk4Nzg4MX0.0YnP2IzkwWT8PH4GBLWU0SzquBRDLK9N4ewY-ruUBzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});